### ISSUE TITLE
Reference params set before iGenomes config is loaded

### ISSUE THREAD

**Issue by efratushava** [nf-core/methylseq#121]
I think in the nextflow.config file, in line   
`bwa_meth_index = params.genome ? params.genomes[ params.genome ].bwa_meth ?: false : false`

Doesn't it have to be 
`  bwa_meth_index = params.genome ? params.genomes[ params.genome ].bwa ?: false : false`

Because in the igenome config, there is no field name bwa_meth, and there **is** a field bwa

**Comment by ewels** [comment]
Hi @efratushava,

Good spot, I'm actually not sure.. I've never personally used the bwameth pipeline with Human data / iGenomes I think.

Ok, looking at https://github.com/brentp/bwa-meth#index - I think that the indices for bwameth are _not_ the same as bwa. Running `bwameth.py index` does call the regular [`bwa index` command](https://github.com/brentp/bwa-meth/blob/eb91baf0ebccf7a5b1ef17b6aae3c560a5776829/bwameth.py#L207-L216), but it's done with a Fasta file that is [converted to a 3-letter code](https://github.com/brentp/bwa-meth/blob/eb91baf0ebccf7a5b1ef17b6aae3c560a5776829/bwameth.py#L168-L204).

So if we try to use regular bwa iGenomes indices for this analysis, it will fail. Or worse, work but give really terrible results.

Ideally, we should add bwa_meth indices to iGenomes for all species. But in the short term, it's possible that people will create their own config files with different species using this notation. So I'm happy to leave the code as it is I think.

Does this make sense? Let me know if you have any suggestions for code / documentation that could be improved.

Phil

**Comment by efratushava** [comment]
Maybe I was not clear.
The iGenome config file doesn't contin a bwa_meth field, so when running the pipeline with the bwameth aligner, it's looking tor the `params.bwa_meth_index` which will always be false because params.genomes[ params.genome ].bwa_meth does not exist.

So, now, in the iGenome config, the bwa field contains a regular bwa index?

**Comment by IsmailM** [comment]
Hi Phil,

I have run into the same issue (when running the bismark aligner option)

Perhaps, the config could be updated to check for aligner type before attempting to set the `bwa_meth_index` value (and look for the `bwa_meth` key that does not exist by default)?

Moreover, there is no `fasta_index` key in the igenomes config. Should we also set this to false.

**Comment by ewels** [comment]
Hi both,

These config keys are not unique to iGenomes. We use the same configuration structure in our custom configs for home-made genome indices. This is why I think it's useful to have that code, even if these keys are not available in the iGenomes config.

I was under the impression that if your current pipeline config doesn't have a key called `bwa_meth` then the channel will be set to false and the index will be built:

https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/nextflow.config#L17

So if `params.genomes[ params.genome ].bwa_meth` evaluates to `false` (such as when it's not set), then `bwa_meth_index` will be set to `false` and the index will be built. Same for Bismark and `fasta_index`.

Am I wrong about this - is the pipeline crashing for you?

> So, now, in the iGenome config, the bwa field contains a regular bwa index?

Yes - used by other pipelines for regular genome alignments. A recent template change added all iGenomes index paths to all pipelines (previously these lines were absent from the pipeline).

Phil

**Comment by IsmailM** [comment]
I initially saw the following error: 

```bash
$ nextflow run nf-core/methylseq -profile docker -resume -c bismark.config --genome 'GRCh37' 
N E X T F L O W  ~  version 19.10.0
Launching `nf-core/methylseq` [grave_almeida] - revision: 40760ecffb [master]
No reference genome index or fasta file specified. Expression: (params.bismark_index || params.fasta)

-- Check script '/home/ucbtmog/.nextflow/assets/nf-core/methylseq/main.nf' at line: 109 or see '.nextflow.log' file for more details
```

Looking back at this, this seems to be less about the `bwa_meth` / `fasta_index` keys not being present in the key, but rather `bismark_index` and `fasta` not being set automatically.

Setting the following manually in my bismark.config fixes the issue:

```bash

params {
  ...
  bismark_index = "${params.igenomes_base}/Homo_sapiens/Ensembl/GRCh37/Sequence/BismarkIndex/"
  fasta = "${params.igenomes_base}/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa"
  ...
}
```

**Comment by efratushava** [comment]
I also had this problem, issue #122

**Comment by ewels** [comment]
Ok, getting somewhere.. @IsmailM - this should _definitely_ work. You're using Bismark with a standard iGenomes reference. `GRCh37` has both a [fasta](https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/conf/igenomes.config#L14) and [Bismark](https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/conf/igenomes.config#L18) ref specified.

Looking at the code a little more closely, I think this is because these values are being set in `nextflow.config` [lines 16-19](https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/nextflow.config#L16-L19) and the iGenomes config is being loaded later in the same file, [lines 100-103](https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/nextflow.config#L100-L103). So there are no iGenomes refs when the variable is set. @efratushava - your issue in #122 is due to the same problem I think.

In other pipelines, such as the RNAseq pipeline, those reference params are [set in `main.nf` instead](https://github.com/nf-core/rnaseq/blob/3b6df9bd104927298fcdf69e97cca7ff1f80527c/main.nf#L120-L127) for exactly this reason.

This used to be the case for the methylseq pipeline too, but it looks like they were moved by @phue in the massive template sync in https://github.com/nf-core/methylseq/pull/92 - so this change would have come out in version 1.4 of the pipeline and broken stuff. Which makes sense.

The fix should be to either use `{}` to defer the execution of those config lines, or better still to just move them back to `main.nf`. I think this is the best approach. It should be pretty easy and I think that this is a serious enough problem to warrant a patch release.

@phue - what do you think?

Phil

**Comment by ewels** [comment]
Prepping a PR now..

**Comment by ewels** [comment]
> I think that this is a serious enough problem to warrant a patch release.

Actually, given that we have merged a couple of PRs, I propose we do a v1.4.1 minor release.

**Comment by jhrf** [comment]
Hi! Thanks for the fantastic work you are doing with methylseq.

I've been trying to run the pipeline today and ran into problems with the iGenomes above. Since finding this thread I have downloaded the latest dev branch to see if it fixed the issues. I'm running into a new issue now.

Using this command:

```
nextflow run local_git_copy/methylseq \
   --reads './*.fq.gz' \
   -profile docker \
   --single-end \
   --genome GRCh38
```

I receive this error message:

```
No reference genome index or fasta file specified. Expression: (params.bismark_index || params.fasta)
 -- Check script 'meth_pipeline/methylseq/main.nf' at line: 117 or see '.nextflow.log' file for more details
```

Here are the relevant entries in the logs:

```
Nov-28 16:07:25.990 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Nov-28 16:07:26.165 [main] WARN  nextflow.script.ScriptBinding - Access to undefined parameter `bismark_index` -- Initialise it to a default value eg. `params.bismark_index = some_value`
Nov-28 16:07:26.172 [main] WARN  nextflow.script.ScriptBinding - Access to undefined parameter `fasta` -- Initialise it to a default value eg. `params.fasta = some_value`
Nov-28 16:07:26.173 [main] DEBUG nextflow.Session - Session aborted -- Cause: No reference genome index or fasta file specified. Expression: (params.bismark_index || params.fasta)
Nov-28 16:07:26.202 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.AssertionError: No reference genome index or fasta file specified. Expression: (params.bismark_index || params.fasta)
        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:417)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
        at Script_c8f6a2b7.runScript(Script_c8f6a2b7:117)
        at nextflow.script.BaseScript.run0(BaseScript.groovy:152)
        at nextflow.script.BaseScript.run(BaseScript.groovy:182)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:217)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:257)
        at nextflow.cli.Launcher.run(Launcher.groovy:457)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

Apologies if this is unrelated, but given the error messages I thought it was relevant

**Comment by efratushava** [comment]
still not working...


```
~% nextflow -log methylseq_try run nf-core/methylseq -with-singularity /tmp/ekushele-singularity/biscuit.img --aligner 'bismark' --reads 'data/fastq_files/*/*sorted_{1,2}.fastq' --genome 'GRCh37' --outdir 'data/nextflow'  
N E X T F L O W  ~  version 19.10.0
Launching `nf-core/methylseq` [shrivelled_golick] - revision: 40760ecffb [master]
Unknown config attribute `params.genomes.GRCh37.bwa_meth` -- check config file: /cs/icore/ekushele/.nextflow/assets/nf-core/methylseq/nextflow.config
```

What's up with this?

**Comment by ewels** [comment]
It is not yet released, try with `-r dev`

**Comment by efratushava** [comment]
You for sure noticed, but I'm just emphasizing-the parameters in the main.nf file should start with params.fasta, params.fasta_index etc... (instead of fasta, fasta_index)

But somehow-it's still not working! The pipeline can't run on my files, which exist for sure!
The script made a link from the files I specified to the working directory, but the fastqc interupts everything, showing the error
`Skipping '149122-cf-M.ben_list.b37.sorted_1.fastq' which didn't exist, or couldn't be read.`
And the file exists!!!

**Comment by ewels** [comment]
Please link to specific lines in the code (permalink with commit hash) if there are bits that you think are wrong. 

Have you pulled the latest version of the dev branch? `nextflow pull`

**Comment by ewels** [comment]
Though the file not existing sounds like it could be a similar problem to the MultiQC issue. I suspect that these are not pipeline specific but relate to containers / Nextflow interaction with the underlying compute infrastructure...

**Comment by efratushava** [comment]
> Please link to specific lines in the code (permalink with commit hash) if there are bits that you think are wrong.

lines 100-103 in main.nf, the lines that were added in the dev version
> 
> Have you pulled the latest version of the dev branch? `nextflow pull`

yes, with `git clone -b dev`

**Comment by ewels** [comment]
https://github.com/nf-core/methylseq/blob/d0dffea55744e9eee0d36444fface0c26e6a7f9a/main.nf#L100-103

**Comment by efratushava** [comment]
> Though the file not existing sounds like it could be a similar problem to the MultiQC issue. I suspect that these are not pipeline specific but relate to containers / Nextflow interaction with the underlying compute infrastructure...

OK. so I think it somehow create a broken symbolic link.

Do you know why?

**Comment by ewels** [comment]
This should now be fixed in `dev` and will be released in 1.4.1 as a minor release.

Thanks all for spotting the error and helping with the fix 👍

**Comment by ewels** [comment]
Hi all,

It took a long time sorry, but we finally just released v1.5 of the pipeline, which includes these fixed.

Apologies for the delay,

Phil
